---
title: "Text Mining Harry Potter Books"
output: html_notebook
---



# Set Up

```{r load-libraries, warning=FALSE, message=FALSE}
library(harrypotter)
library(tidyverse)
library(tidytext)
```

# Data Pull

```{r}
# Titles of the books
titles <- c(
  "Philosopher's Stone", 
  "Chamber of Secrets", 
  "Prisoner of Azkaban",
  "Goblet of Fire", 
  "Order of the Phoenix", 
  "Half-Blood Prince",
  "Deathly Hallows"
  )

# putting each of the books into a list
books <- list(
  philosophers_stone, 
  chamber_of_secrets, 
  prisoner_of_azkaban,
  goblet_of_fire, 
  order_of_the_phoenix, 
  half_blood_prince,
  deathly_hallows
  )

# Each book is an array in which each value in the array is a chapter 
harry_potter_df <- tibble()
for(i in seq_along(titles)) {
  
  temp <- tibble(
    chapter = seq_along(books[[i]]),
                  text = books[[i]]) %>%
    unnest_tokens(word, text) %>%
    
    #tokenize each chapter into words
    mutate(book = titles[i]) %>%
    select(book, everything())
  
  harry_potter_df <- rbind(harry_potter_df, temp)
}

# Check data process
head(harry_potter_df, n = 4)
```

# Exploratory Data Analysis


First up, how many words are in each Harry Potter Book?
```{r}
word_count_plt <- harry_potter_df %>% 
  mutate(book = fct_relevel(book, "Philosopher's Stone", "Chamber of Secrets",
                                    "Prisoner of Azkaban", "Goblet of Fire",
                                    "Order of the Phoenix", "Half-Blood Prince",
                                    "Deathly Hallows")) %>% 
  group_by(book) %>%
  summarise(word_count = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = book, y = word_count, group = 1, fill = book)) + 
    geom_col(color = "black") + 
    geom_text(aes(label = word_count), vjust = -1) + 
    expand_limits(y = c(0, 300000)) + 
    scale_y_continuous(labels = scales::comma) + 
    theme_minimal() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.text = element_text(face = "bold", size = 12),
      axis.title = element_text(face = "bold", size = 12),
      plot.title = element_text(face = "bold", size = 16),
      plot.subtitle = element_text(face = "bold", size = 14),
      legend.position = "none"
    ) + 
    labs(
      title = "Harry Potter: Word Count by Book",
      subtitle = "Order of the Pheonix contains the most words",
      y = "Word Count",
      x = "",
      caption = "*Data scourced & pull using https://github.com/bradleyboehmke/harrypotter"
    )


word_count_plt
```

```{r, fig.width=9, fig.height=6}
harry_potter_df %>% 
  anti_join(stop_words, by = "word") %>% 
  inner_join(get_sentiments("afinn"), by = "word") %>% 
  group_by(book, chapter) %>% 
  summarise(
    sentiment = mean(value)
  ) %>% 
  ungroup() %>% 
  mutate(book = fct_relevel(book, "Philosopher's Stone", "Chamber of Secrets",
                                  "Prisoner of Azkaban", "Goblet of Fire",
                                  "Order of the Phoenix", "Half-Blood Prince",
                                  "Deathly Hallows")) %>%
  ggplot(aes(x = sentiment, fill = book)) + 
    geom_density(color = "black", alpha = .5) + 
    facet_wrap(. ~ book, scales = "free", nrow = 2) + 
    theme_minimal() +
    theme(
      legend.position = "none"
    ) + 
    labs(
      title = "Harry Potter: Mean of Distribution Sentiment by Chapter",
      subtitle = "",
      x = "Sentiment",
      y = "Density"
    )
  
```


